seed: 9

federation:
  num_rounds: 50
  local_epochs: 5
  batch_size: 32

training:
  lr: 0.001
  optimizer: 'adam'

model:
  name: 'xpatch'    #'xpatch', 'rnn', 'lstm', 'gru', 'mlp'

results:
  save_dir_prefix: 'result/'

privacy:
  enabled: true     # 是否启用差分隐私
  clipping_norm: 1.5      # DP所必需的梯度裁剪 L2 范数

  noise_sigma:
    seasonal: 0.001
    trend: 0.005

aggregation:
  name: 'fedavg'  # 'fedavg', 'fedprox'
  mu: 0.01               # FedProx专用，近端项系数

clustering:
  enabled: true
  num_clusters: 3
  recluster_every_n_rounds: 10 # 每隔多少轮重新计算一次聚类
  cluster_on: 'both'  # 依据哪个模型组件进行聚类 ('trend', 'seasonal', 或 'both')


# 数据与设备设置
#data:
#  mode: 'multi_file'  # 使用多文件模式
#  files:
#    - 'data/batch-1.xlsx'
#    - 'data/batch-2.xlsx'
#    - 'data/batch-3.xlsx'
##    - 'data/batch-4.xlsx'
##    - 'data/batch-5.xlsx'
#  window_size: 50
#  pre_len: 200
#  max_capacity: 2.0
#  enc_in: 6
#  device: 'cuda'

data:
 mode: 'single_file_multi_client'  # 使用单文件多客户端模式
 single_file: 'data/batch-1.xlsx'  # 指定单个数据文件
 window_size: 50
 pre_len: 200
 max_capacity: 2.0
 enc_in: 6
 device: 'cuda'


